# Generated by Django 4.0.4 on 2022-05-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icreat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icreat',
            name='goal_research',
            field=models.CharField(blank=True, max_length=20, verbose_name='전체목표연구대상자수'),
        ),
        migrations.AlterField(
            model_name='icreat',
            name='period',
            field=models.CharField(blank=True, max_length=20, verbose_name='연구기간'),
        ),
        migrations.AlterField(
            model_name='icreat',
            name='trial',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='임상시험단계(연구모형)'),
            preserve_default=False,
        ),
    ]
